# Form implementation generated from reading ui file 'Main1.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from backend.loadContract import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 100, 631, 421))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(60, 40, 461, 181))
        self.tableWidget.setObjectName("tableWidget")

        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)

        self.loaddata()

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def queryChain(self):
        pvsTx = dtContract.functions.retrieve().call()[3]
        history = []
        while pvsTx:
            tx = w3.eth.get_transaction(pvsTx)
            try:
                obj, params = dtContract.decode_function_input(tx["input"])
                print(params)
                params["_time"] = decrypt(params["_time"])
                params["_userID"] = decrypt(params["_userID"])
                pvsTx = params["_previousTx"]
                history.append(params)
            except:
                pvsTx = False
        return history

    def loaddata(self):

        trans = self.queryChain()
        row = 0
        self.tableWidget.setRowCount(len(trans))
        for transaction in trans:
            self.tableWidget.setItem(
                row, 0, QtWidgets.QTableWidgetItem(str(transaction["_time"]))
            )
            self.tableWidget.setItem(
                row, 1, QtWidgets.QTableWidgetItem(str(transaction["_hashNumber"]))
            )
            self.tableWidget.setItem(
                row, 2, QtWidgets.QTableWidgetItem(str(transaction["_userID"]))
            )
            self.tableWidget.setItem(
                row, 3, QtWidgets.QTableWidgetItem(str(transaction["_previousTx"]))
            )
            row = row + 1

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GEthereum"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Change History")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "About Us")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
