# Form implementation generated from reading ui file 'Welcome.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from blocks import Ui_Window1
# from change_hist import 

class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Window1()
        self.ui.setupUi(self.window)
        self.window.show()

    # def openWindow2(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_Window1()
    #     self.ui.setupUi2(self.window2)
    #     self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.view_chain = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openWindow())
        self.view_chain.setGeometry(QtCore.QRect(200, 150, 100, 50))
        self.view_chain.setObjectName("view_chain")
        self.changes = QtWidgets.QPushButton(self.centralwidget)
        self.changes.setGeometry(QtCore.QRect(200, 250, 100, 50))
        self.changes.setObjectName("changes")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 90, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Big Caslon")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionFile_2 = QtGui.QAction(MainWindow)
        self.actionFile_2.setObjectName("actionFile_2")
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.view_chain.setText(_translate("MainWindow", "View Blockchain!"))
        self.changes.setText(_translate("MainWindow", "View Changes!"))
        self.label.setText(_translate("MainWindow", "Welcome"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionFile_2.setText(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
